[package]
name = "leptos-controls-core"
version = "0.1.0"
edition = "2021"

[dependencies]
leptos = { version = "0.6" }
thaw_utils = { version = "0.0.6", optional = true }

[features]
thaw = ["dep:thaw_utils"]
