[package]
name = "leptos-controls-core"
version.workspace = true
edition.workspace = true

[dependencies]
leptos = { version = "0.6" }
thaw_utils = { version = "0.0.6", optional = true }

[features]
thaw = ["dep:thaw_utils"]
